### ISSUE TITLE
Complete transition into using poetry and more

### ISSUE THREAD

**Issue by ificiana** [nficano/humps#287]
# Describe the solution you'd like
As mentioned earlier by @ronnie-llamado in #235:
The PR accompanying this issue aims to complete the process. Moreover, it explicitly adds support for Python 3.11

# Tasks
**To Do**
- [x] Move PyPI information (version, classifiers, etc) over to pyproject.toml
- [x] Remove extraneous pipenv files (when the transition is complete)
- [x] Update Makefile for versioning

**Up for Discussion**
> - [ ]  Add new GitHub Actions workflow to push the package to PyPI on a new tag
> I personally prefer the CLI commands for publishing, but if needed we can update the workflow as needed.

**Extras**
- [x] Add support for Python 3.11 

# Additional context

**Testing the versioning system: Example Output**
```bash
$ poetry version
pyhumps 3.8.0
$ make deploy-patch
  poetry version patch
  Bumping version from 3.8.0 to 3.8.1
  git commit -m 'Bump version: 3.8.0 → 3.8.1' pyproject.toml
  [master XXXXXXX] Bump version: 3.8.0 → 3.8.1
   1 file changed, 1 insertion(+), 1 deletion(-)
  .
  .  (omitting results)
  .
  poetry publish -r test-pypi
  # this is a mock deployment, published to TestPyPI
  
  Publishing pyhumps (3.8.1) to test-pypi
   - Uploading pyhumps-3.8.1-py3-none-any.whl 0%
   - Uploading pyhumps-3.8.1-py3-none-any.whl 57%
   - Uploading pyhumps-3.8.1-py3-none-any.whl 100%
   - Uploading pyhumps-3.8.1.tar.gz 0%
   - Uploading pyhumps-3.8.1.tar.gz 100%
```
---
[pyhumps mock](https://test.pypi.org/project/pyhumps/)
---
![image](https://user-images.githubusercontent.com/78205638/198898971-77b46e27-751e-4432-87cf-13cd22e443a8.png)

**Comment by ificiana** [comment]
> * [?] Add a new GitHub Actions workflow to push the package to PyPI on a new tag
>   I prefer the CLI commands for publishing, but if needed we can update the workflow as needed.

https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries
@nficano this step needs the API key as a repo secret, we can use this workflow depending on what you're comfortable with...
